echo Windows Registry Editor Version 5.00>>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects]>>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shell]>>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shell\显示隐藏扩展名]>>"%TEMP%\显示隐藏扩展名.reg"
echo @="显示扩展名">>"%TEMP%\显示隐藏扩展名.reg"
echo "Extended"="">>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shell\显示隐藏扩展名\command]>>"%TEMP%\显示隐藏扩展名.reg"
echo @=hex(2):77,00,73,00,63,00,72,00,69,00,70,00,74,00,2e,00,65,00,78,00,65,00,20,\>>"%TEMP%\显示隐藏扩展名.reg"
echo 00,25,00,73,00,79,00,73,00,74,00,65,00,6d,00,72,00,6f,00,6f,00,74,00,25,00,\>>"%TEMP%\显示隐藏扩展名.reg"
echo 5c,00,3e,66,3a,79,90,96,cf,85,69,62,55,5c,0d,54,2e,00,76,00,62,00,73,00,20,\>>"%TEMP%\显示隐藏扩展名.reg"
echo 00,22,00,25,00,31,00,22,00,00,00>>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shellex]>>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shellex\ContextMenuHandlers]>>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shellex\ContextMenuHandlers\Send To]>>"%TEMP%\显示隐藏扩展名.reg"
echo @="{7BA4C740-9E81-11CF-99D3-00AA004AE837}">>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shellex\PropertySheetHandlers]>>"%TEMP%\显示隐藏扩展名.reg"
echo [HKEY_CLASSES_ROOT\AllFilesystemObjects\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}]>>"%TEMP%\显示隐藏扩展名.reg"
echo @="">>"%TEMP%\显示隐藏扩展名.reg"
START /WAIT REGEDIT /S "%TEMP%\显示隐藏扩展名.reg"
del /q "%TEMP%\显示隐藏扩展名.reg"
echo Dim WSHShell>>"%systemroot%\显示隐藏扩展名.vbs"
echo Set WSHShell = WScript.CreateObject("WScript.Shell")>>"%systemroot%\显示隐藏扩展名.vbs"
echo if WSHShell.RegRead("HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\HideFileExt") = 0 then>>"%systemroot%\显示隐藏扩展名.vbs"
echo WSHShell.RegWrite "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\HideFileExt", "1", "REG_DWORD">>"%systemroot%\显示隐藏扩展名.vbs"
echo WSHShell.RegWrite "HKCR\AllFilesystemObjects\shell\显示隐藏扩展名\", "显示扩展名", "REG_SZ">>"%systemroot%\显示隐藏扩展名.vbs"
echo WSHShell.SendKeys "{F5}+{F10}e">>"%systemroot%\显示隐藏扩展名.vbs"
echo else>>"%systemroot%\显示隐藏扩展名.vbs"
echo WSHShell.RegWrite "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\HideFileExt", "0", "REG_DWORD">>"%systemroot%\显示隐藏扩展名.vbs"
echo WSHShell.RegWrite "HKCR\AllFilesystemObjects\shell\显示隐藏扩展名\", "隐藏扩展名", "REG_SZ">>"%systemroot%\显示隐藏扩展名.vbs"
echo WSHShell.SendKeys "{F5}+{F10}e">>"%systemroot%\显示隐藏扩展名.vbs"
echo end if>>"%systemroot%\显示隐藏扩展名.vbs"
echo Set WSHShell = Nothing>>"%systemroot%\显示隐藏扩展名.vbs"
echo WScript.Quit(0)>>"%systemroot%\显示隐藏扩展名.vbs"
